### ISSUE TITLE
[Bug]: Target Dummy Hp% set to 0

### ISSUE THREAD

**Issue by Kanubiz** [jdsmith2816/delvui#3]
### What are you trying to do?

targeting a target dummy and check hp %

### What is the expected behavior?

Retrieve the correct hp%

### What actually happened?

Retrieved 0 on currenthp/maxhp

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by jdsmith2816** [comment]
Fixed
